version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    networks:
      - yuhu

  yuhu-api:
    container_name: api
    entrypoint: ./entrypoint.sh
    build:
      context: .
    env_file:
      - ./.env
    volumes:
      - .:/code:rw
    ports:
      - 8000:8000
    networks:
      - yuhu
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=yuhu_api worker -l INFO
    depends_on:
      - redis
    networks:
      - yuhu

networks:
  yuhu:
    external: true
